name: Docker Build

on:
  push:
  pull_request:
  workflow_dispatch: # 手動觸發工作流程

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image (Dockerfile)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false # 這裡設定為 false，因為您沒有指定要推送
          tags: ${{ github.repository }}:latest

      - name: Build the second Docker image (Dockerfile.app2)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.app2
          push: false # 這裡設定為 false，因為您沒有指定要推送
          tags: ${{ github.repository }}:app2-latest
