name: Docker Build and Push

on:
  push:
    branches: [main] # 只有當程式碼推送到 main 分支時才觸發 (您可以根據需要修改)
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write # 授予寫入 GitHub Packages 的權限 (如果推送至 GHCR)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image (Dockerfile)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:latest

      - name: Build and push the second Docker image (Dockerfile.app2)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.app2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:app2-latest
